@startuml
' Title for the diagram
title System Sequence Diagram: US231 - List Public Figures

actor "CRM Collaborator" as User
participant ":System" as System

activate User
User -> System : requestsPublicFigureList()
activate System

System -> System :  getPublicFigures()

System --> User : displaysPublicFigureList(figures)
deactivate System

deactivate User

@enduml