@startuml
' Title for the diagram
title Sequence Diagram: US231 - List Public Figures

actor "CRM Collaborator" as User
participant "FigureListUI" as UI
participant "FigureListController" as Controller
participant "FigureApplicationService" as AppService
participant "FigureRepository" as Repo
database "Database" as DB

activate User
User -> UI : requestsPublicFigureList()
activate UI

UI -> Controller : getPublicFigures()
activate Controller

Controller -> AppService : listPublicFigures()
activate AppService

AppService -> Repo : findAvailablePublicFigures()
activate Repo
Repo -> DB : Executes query(...)
activate DB
DB --> Repo : Returns Figure records/data
deactivate DB
Repo --> AppService : figures: List<Figure>
deactivate Repo

AppService -> AppService : Map figures to DTOs
AppService --> Controller : dtoList: List<FigureListDTO>
deactivate AppService

Controller --> UI :dtoList
deactivate Controller

UI --> User : displayPublicFigureList(dtoList)
deactivate UI
deactivate User

@enduml