@startuml

skinparam handwritten false
skinparam shadowing false
skinparam roundcorner 10
skinparam class {
    BackgroundColor PaleTurquoise
    ArrowColor Navy
    BorderColor Navy
    BorderThickness 1
}
skinparam package {
    BackgroundColor LightSteelBlue
    BorderColor Navy
    FontColor Navy
}
skinparam enum {
     BackgroundColor LightGoldenrodYellow
     BorderColor OrangeRed
}
skinparam stereotypeCBackgroundColor YellowGreen

package "Client Aggregate" <<Folder>> {
    class Client <<ER>> {
      
    }

    class Representative <<E>> {
        
    }

    class Address <<VO>> {
        Street : String
        City : String
        Country : String
    }
    Address "1" *-- "1" ZipCode : has >

    class ZipCode <<VO>> {
        ZipCode : String
    }
    class Name_1 <<VO>> {
        FirstName : String
        LastName : String
    }
    class Phone <<VO>> {
        PhoneNumber : String
    }
    class Email <<VO>> {
        EmailAddress : String
    }
    class VAT <<VO>> {
        VATNumber : String
    }
    class Position <<VO>> {
        Position : String
    }
    enum Status <<VO>> {
        VIP
        REGULAR
        DELETED
        INFRINGEMENT
        CREATED
    }
}

package "ShowRequest Aggregate" <<Folder>> {
    class ShowRequest <<ER>> {
      
    }

    class Place_1 <<VO>> {
        PlaceName : String
    }
    Place_1 "1" *-- "1" Geolocation_1 : contains >

    class Geolocation_1 <<VO>> {
        Longitude : Double
        Latitude : Double
    }

    class Date_3 <<VO>> {
        Date : LocalDateTime
    }

    class Duration_2 <<VO>> {
        Time : Duration
    }

    class DronesRequested <<VO>> {
        Quantity : Integer {>0}
    }

    class Description_1 <<VO>> {
        DocumentReference : String
    }

    enum ShowRequestStatus <<VO>> {
      SUBMITTED
      UNDER_ANALYSIS
      APPROVED
      REJECTED
      IN_PRODUCTION
      COMPLETED
      CANCELLED
    }
}

ShowRequest "1..*" -- "1" Client : references > (via VAT)
ShowRequest "1..*" -- "1" Representative : references > (via RepresentativeID)

Client "1" o-- "1..*" Representative : has >
Client "1" *-- "1" VAT : identified by >
Client "1" *-- "1" Status : has >
Client "1" *-- "1" Address : has >
Client "1" *-- "1" Name_1 : identified by >
Client "1" *-- "1" Phone : has >
Client "1" *-- "1" Email : uses >

Representative "1" *-- "1" Name_1 : has name >
Representative "1" *-- "1" Phone : has >
Representative "1" *-- "1" Email : uses >
Representative "1" *-- "1" Position : holds >

ShowRequest "1" *-- "1" Place_1 : occurs at >
ShowRequest "1" *-- "1" Date_3 : scheduled for >
ShowRequest "1" *-- "1" Duration_2 : requested duration >
ShowRequest "1" *-- "1" DronesRequested : requires >
ShowRequest "1" *-- "1" Description_1 : described by >
ShowRequest "1" *-- "1" ShowRequestStatus : has status >

title US230 Register Show Request - Domain Model

@enduml