@startuml US230_RegisterShowRequest_SSD

title System Sequence Diagram: US230 - Register Show Request

actor "CRM Collaborator" as User
participant ":System" as System

activate User
User -> System : initiatesShowRequestRegistration()
activate System

System --> User : requestsCustomerSelection(activeCustomersList)
deactivate System

User -> System : selectCustomer(customerIdentifier)
activate System

System --> User : requestsShowDetails(placePrompt, datePrompt, timePrompt, durationPrompt, dronePrompt, descriptionPrompt)
deactivate System

User -> System : submitShowRequestDetails(place, dateTime, duration, droneCount, descriptionRef)
activate System

System -> System : processShowRequestCreation(details)

System --> User : displayRegistrationSuccess(confirmationInfo)

deactivate System
deactivate User

@enduml