@startuml design/class-diagram-235.svg

skinparam stereotypeCBackgroundColor YellowGreen

class ListClientShowRequestsUI {
  - controller : ListClientShowRequestsController
  + doShow()
}

class ListClientShowRequestsController {
  - clientRepository : ClientRepository
  - showRequestRepository : ShowRequestRepository
  + getAllClientsForSelection() : Iterable<Client>
  + listShowRequestsForClient(clientVAT : VAT) : Iterable<ShowRequestSummaryDTO>
}

class ShowRequestSummaryDTO <<DTO>> {
  + submissionDate : LocalDateTime
  + placeName : String
  + status : ShowRequestStatus
}

interface ClientRepository <<Repository>> {
  + findAll() : Iterable<Client>
  + findByVAT(vat : VAT) : Optional<Client>
}

interface ShowRequestRepository <<Repository>> {
  + findByClientVAT(clientVAT : VAT) : Iterable<ShowRequest>
}

class Client <<AggregateRoot>> {
  + vat() : VAT
  + name() : Name_1
}

class ShowRequest <<Entity>> {
  + customerVAT() : VAT
  + place() : Place_1
  + submissionDate() : LocalDateTime
  + status() : ShowRequestStatus
}

class VAT <<ValueObject>> {}
class Name_1 <<ValueObject>> {}
class Place_1 <<ValueObject>> {}
enum ShowRequestStatus <<ValueObject>> {}

ListClientShowRequestsUI ..> ListClientShowRequestsController
ListClientShowRequestsController ..> ClientRepository
ListClientShowRequestsController ..> ShowRequestRepository
ListClientShowRequestsController ..> ShowRequestSummaryDTO : creates
ShowRequestRepository ..> ShowRequest : finds
ClientRepository ..> Client : finds
ShowRequest --> VAT : uses
Client --> VAT : uses
Client --> Name_1 : has
ShowRequest --> Place_1 : uses
ShowRequest --> ShowRequestStatus : uses

@enduml